# Generated by Django 2.1.5 on 2019-02-21 11:48

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название конференции')),
                ('date', models.DateField(verbose_name='Дата проведения')),
                ('place', models.CharField(max_length=100, verbose_name='Место проведения')),
                ('completed', models.BooleanField(verbose_name='Проведена')),
            ],
            options={
                'verbose_name_plural': 'Конференции',
                'verbose_name': 'Конференция',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=100, verbose_name='ФИО')),
                ('job', models.CharField(max_length=100, verbose_name='Место работы')),
                ('jobplace', models.CharField(max_length=100, verbose_name='Должность')),
                ('tel', models.CharField(max_length=100, verbose_name='Телефон')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
                ('membership', models.BooleanField(verbose_name='Членство в РСПС')),
            ],
            options={
                'verbose_name_plural': 'Участники',
                'verbose_name': 'Участник',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='upload/', verbose_name='Фото')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название публикации')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текст публикации')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name_plural': 'Публикации',
                'verbose_name': 'Публикация',
            },
        ),
        migrations.AddField(
            model_name='photo',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Post'),
        ),
        migrations.AddField(
            model_name='conference',
            name='members',
            field=models.ManyToManyField(to='mainapp.Member', verbose_name='Участники'),
        ),
    ]
