# Generated by Django 2.1.5 on 2019-02-06 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название конференции')),
                ('date', models.DateField(verbose_name='Дата проведения')),
                ('place', models.CharField(max_length=100, verbose_name='Место проведения')),
                ('completed', models.BooleanField(verbose_name='Проведена')),
            ],
            options={
                'verbose_name': 'Конференция',
                'verbose_name_plural': 'Конференции',
            },
        ),
    ]
