# Generated by Django 2.1.5 on 2019-02-21 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='short_description',
            field=models.CharField(default='', max_length=100, verbose_name='Краткое описание'),
            preserve_default=False,
        ),
    ]
