# Generated by Django 2.1.5 on 2019-02-06 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=100, verbose_name='ФИО')),
                ('job', models.CharField(max_length=100, verbose_name='Место работы')),
                ('jobplace', models.CharField(max_length=100, verbose_name='Должность')),
                ('tel', models.CharField(max_length=100, verbose_name='Телефон')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
                ('membership', models.BooleanField(verbose_name='Членство в РСПС')),
            ],
            options={
                'verbose_name_plural': 'Участники',
                'verbose_name': 'Участник',
            },
        ),
    ]
