# Generated by Django 2.1.5 on 2019-02-22 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_post_short_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='membership',
        ),
        migrations.AlterField(
            model_name='post',
            name='short_description',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Краткое описание'),
        ),
    ]
