# Generated by Django 2.1.5 on 2019-02-07 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.Member', verbose_name='Участники конференции'),
        ),
    ]
