# Generated by Django 2.1.5 on 2019-02-22 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0003_auto_20190222_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='city',
            field=models.CharField(default='MOSCOW', max_length=100, verbose_name='Город проживания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='Email'),
        ),
    ]
