# Generated by Django 2.1.5 on 2019-02-07 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_conference_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conference',
            name='member',
        ),
        migrations.AddField(
            model_name='conference',
            name='members',
            field=models.ManyToManyField(to='mainapp.Member', verbose_name='Участники'),
        ),
    ]
