# Generated by Django 2.1.5 on 2019-02-22 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainapp', '0003_auto_20190222_0847'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Новый', 'Новый член РСПС'), ('Заявлен', 'Заявлен на утверждение Президиумом РСПС'), ('Одобрен', 'Утвержден Президиумом РСПС'), ('Выдан сертификат', 'Выдан сертификат РСПС')], default='Новый', max_length=20)),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.Member')),
            ],
        ),
    ]
