# Generated by Django 2.1.5 on 2019-02-22 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membership',
            options={'verbose_name': 'статус членства', 'verbose_name_plural': 'статусы членства'},
        ),
    ]
